version: '3.8'

services:
  crypto-bot:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: crypto-trading-bot
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    env_file:
      - .env
    volumes:
      # 挂载日志目录到宿主机
      - ./logs:/app/logs
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - crypto-bot-network

networks:
  crypto-bot-network:
    driver: bridge

# 可选：如果需要数据持久化
volumes:
  logs:
    driver: local
